### ISSUE TITLE
Thanks for the plugin

### ISSUE THREAD

**Issue by Kocardi** [pommes-frites/piwigo-facetag#2]
I made two icons if you want
sorry for my English
Thanks google translator

**Comment by flop25** [comment]
@pommes-frites Hello  Here is the thread in French http://fr.piwigo.org/forum/viewtopic.php?pid=220082#p220082 if you want to take a look
@Kocardi I'm watching that Issue to help if there is a misunderstanding French/English / Je surveille ce ticket github si vous voulez en cas de soucis français/anglais ;)

**Comment by Kocardi** [comment]
@flop25 Ok merci

**Comment by pommes-frites** [comment]
Hi Kocardi,

I didn't invest much time in button design, as you might have recognized. It's difficult, because often one icon looks good only with one template. Thats why the plugin uses a different icon in bootstrap darkroom theme, which I use. 

However, If you have icons I can use for the plugin, it would be nice if you provide them in some way.

Thanks,

pommes

**Comment by Kocardi** [comment]
hi pommes-frites
You can download icons here
https://kervian.freeboxos.fr:44764/share/5a-WBiSDN93ljUsl/
Valable jusqu'au 06/02/2017 à 12:05:14
The third icon it is to identify the photos which(who) already possede a facetag
Thanks

**Comment by pommes-frites** [comment]
I downloaded the icons and try to integrate them in the next version.

Thank you!

pommes
